name: edutrack_parent
description: "EduTrack Guardian App — monitor your child's attendance in real time."
publish_to: 'none'
version: 1.0.10+11

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  flutter_local_notifications: ^19.5.0
  package_info_plus: ^8.3.1
  path_provider: ^2.1.5
  open_filex: ^4.5.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png
