plugins {
    id "com.android.application"
}

android {
    namespace "ph.gov.sipalay.attendance"
    compileSdk 35

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    defaultConfig {
        applicationId "ph.gov.sipalay.attendance"
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName "1.0.2"
    }
}

dependencies {
    implementation "androidx.core:core:1.13.1"
    implementation "androidx.work:work-runtime:2.9.1"
}
